version: 2
jobs:
  build:
    working_directory: ~/kerneladmin
    docker:
      - image: debian:stable
    steps:
      - checkout
      - run:
          name: "Install ansible"
          command: apt update && apt install -y ansible
      - run:
          command: printf "[debian]\nlocalhost ansible_connection=local" > hosts && ansible-playbook site.yml -i hosts -e git_email=email@email.email
