- name: Copy apt sources.list
  copy:
    src: sources.list
    dest: /etc/apt/sources.list
  become: true

- name: Perform dist upgrade
  apt:
    upgrade: dist
    update_cache: yes
  become: true

- name: Install apt packages
  apt:
    pkg: "{{ item }}"
    state: installed
  become: true
  with_items: "{{ packages + apt_packages }}"

- name: Copy udev rules
  copy:
    src: 70-u2f.rules
    dest: /etc/udev/rules.d/70-u2f.rules
  become: true
  ignore_errors: True

- name: Set gnome shell favorites
  command: 'gsettings set org.gnome.shell favorite-apps "{{ favorite_apps|gvariant }}"'
  ignore_errors: True
