- name: Add apt sources
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  become: true
  with_items: "{{ apt_sources }}"

- name: Add fish shell apt key
  apt_key:
    repo: ppa:fish-shell/release-2
  become: true

- name: Download dist upgrade
  shell: apt-get --download-only dist-upgrade -y
  become: true

- name: Perform dist upgrade
  apt:
    upgrade: dist
  become: true

- name: Install apt packages
  apt:
    pkg: "{{ item }}"
    state: installed
  become: true
  with_items: "{{ apt_packages }}"
