- name: Add fish shell apt key
  apt_key:
    repo: ppa:fish-shell/release-2
  become: true

- name: Install apt packages
  apt:
    pkg: "{{ item }}"
    state: installed
  become: true
  with_items: "{{ apt_packages }}"
