apt_packages:
  - cloc
  - cmake
  - fish
  - git
  - golang
  - graphviz
  - htop
  - lynis
  - mosh
  - neovim
  - pandoc
  - python-pip
  - python3
  - python3-pip
  - python3-venv
  - silversearcher-ag
  - tmux
