dotfiles: "{{ ansible_env.HOME }}/.dotfiles"
xdg_config_home: "{{ ansible_env.HOME }}/.config"
home: "{{ ansible_env.HOME }}"
user: "{{ ansible_env.USER }}"
dotfiles_repository: https://github.com/justuswilhelm/dotfiles.git
git_config:
  push.default: simple
  core.editor: nvim
  core.excludesfile: "{{ home }}/.gitignore"
  merge.conflictstyle: diff3
  user.name: Justus Perlwitz
npm_packages:
  - bower
  - elm
  - elm-test
  - eslint
  - less
  - lesshint
  - yuglify
go_packages:
  - github.com/golang/lint/golint
  - github.com/justuswilhelm/autojump
pip2_packages:
  - isort
  - neovim
pip3_packages:
  - isort
  - neovim
  - pip
  - setuptools
  - wheel
  - xattr
